# Generated by Django 3.0.7 on 2020-06-18 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_date', models.DateField(default=datetime.date(2020, 6, 18))),
                ('patient_name', models.CharField(max_length=50)),
                ('health_care', models.CharField(default='', max_length=50)),
                ('Fee', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=3000)),
            ],
        ),
    ]
