# Generated by Django 3.0.7 on 2020-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestbasic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
